[project]
name = 'chantra_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.ERC721_token_support]
path = 'contracts/ERC721_token_support.clar'
clarity_version = 2
epoch = 2.5

[contracts.access_control]
path = 'contracts/access_control.clar'
clarity_version = 2
epoch = 2.5

[contracts.content]
path = 'contracts/content.clar'
clarity_version = 2
epoch = 2.5

[contracts.depot_with_min_or_max_contraints]
path = 'contracts/depot_with_min_or_max_contraints.clar'
clarity_version = 2
epoch = 2.5

[contracts.feea]
path = 'contracts/feea.clar'
clarity_version = 2
epoch = 2.5

[contracts.multiple_proposal]
path = 'contracts/multiple_proposal.clar'
clarity_version = 2
epoch = 2.5

[contracts.ownership_transfer_wallet]
path = 'contracts/ownership_transfer_wallet.clar'
clarity_version = 2
epoch = 2.5

[contracts.personalized]
path = 'contracts/personalized.clar'
clarity_version = 2
epoch = 2.5

[contracts.privacy]
path = 'contracts/privacy.clar'
clarity_version = 2
epoch = 2.5

[contracts.research_fund]
path = 'contracts/research_fund.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
