[project]
name = 'chantra_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.content]
path = 'contracts/content.clar'
clarity_version = 2
epoch = 2.5

[contracts.personalized]
path = 'contracts/personalized.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
